### ISSUE TITLE
Unable to BUILD the container with the provided DockerFile

### ISSUE THREAD

**Issue by lastcron** [qredo/signing-agent#6]
Steps to reproduce:

1) git clone the repo
2) get into the dockerfiles folder
3) run docker build . --tag qredo-signing-agent
4) Get the following error:
[+] Building 2.6s (17/20)                                                                                                      
 => [internal] load build definition from Dockerfile                                                                      0.0s
 => => transferring dockerfile: 2.28kB                                                                                    0.0s
 => [internal] load .dockerignore                                                                                         0.0s
 => => transferring context: 2B                                                                                           0.0s
 => [internal] load metadata for docker.io/library/alpine:latest                                                          1.5s
 => [internal] load metadata for docker.io/library/golang:alpine                                                          1.5s
 => [auth] library/alpine:pull token for registry-1.docker.io                                                             0.0s
 => [auth] library/golang:pull token for registry-1.docker.io                                                             0.0s
 => [certs 1/2] FROM docker.io/library/alpine@sha256:f271e74b17ced29b915d351685fd4644785c6d1559dd1f2d4189a5e851ef753a     0.0s
 => [go_builder 1/7] FROM docker.io/library/golang:alpine@sha256:2381c1e5f8350a901597d633b2e517775eeac7a6682be39225a93b2  0.0s
 => [internal] load build context                                                                                         0.0s
 => => transferring context: 2.78kB                                                                                       0.0s
 => CACHED [certs 2/2] RUN apk add -U --no-cache ca-certificates                                                          0.0s
 => CACHED [stage-2 1/4] COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/                             0.0s
 => CACHED [go_builder 2/7] RUN apk update && apk add         ca-certificates         cmake         g++         gcc       0.0s
 => CACHED [go_builder 3/7] RUN echo Building Milagro Crypt C library &&     git clone https://github.com/apache/incubat  0.0s
 => [go_builder 4/7] COPY . /src/signing-agent                                                                            0.1s
 => [go_builder 5/7] WORKDIR /src/signing-agent                                                                           0.0s
 => [go_builder 6/7] RUN ls -la                                                                                           0.6s
 => ERROR [go_builder 7/7] RUN CGO_ENABLED=1     GO111MODULES=on     go build       -tags debug       -ldflags "-w -link  0.3s
------                                                                                                                         
 > [go_builder 7/7] RUN CGO_ENABLED=1     GO111MODULES=on     go build       -tags debug       -ldflags "-w -linkmode external -extldflags '-static' -X 'main.buildDate=$BUILD_DATE'                                                             -X 'main.buildVersion="$(git rev-list -1 --abbrev-commit HEAD)"'                                                             -X 'main.buildType=$BUILD_TYPE'"       -o signing-agent       github.com/qredo/signing-agent/tree/master/cmd/service:
#17 0.234 fatal: not a git repository (or any of the parent directories): .git
#17 0.248 no required module provides package github.com/qredo/signing-agent/tree/master/cmd/service: go.mod file not found in current directory or any parent directory; see 'go help modules'
------
executor failed running [/bin/sh -c CGO_ENABLED=1     GO111MODULES=on     go build       -tags debug       -ldflags "-w -linkmode external -extldflags '-static' -X 'main.buildDate=$BUILD_DATE'                                                             -X 'main.buildVersion="$(git rev-list -1 --abbrev-commit HEAD)"'                                                             -X 'main.buildType=$BUILD_TYPE'"       -o signing-agent       github.com/qredo/signing-agent/tree/master/cmd/service]: exit code: 1

**Comment by krisdaniels1** [comment]
Please have a look at the provided build.sh file, you don't need to cd into the dockerfiles folder, you need to run docker build from the root of the repository -> 
```
docker build -f ./dockerfiles/Dockerfile -t qredo-signing-agent .
```
